### ISSUE TITLE
Multi thread problems

### ISSUE THREAD

**Issue by walwalwalides** [digao-dalpiaz/DzSocket#1]
Nice Work,But i think It's Better to use  TWSocket,TWSocketServer From(ICS Product) cause of multi-thread safety Problems,u can get from this Link: http://www.overbyte.eu/frame_index.html ,it's freeware with full source code for all Delphi by François PIETTE .Good Continuation 👍

**Comment by digao-dalpiaz** [comment]
Hey,
Yes, I agree with you.

But even so, you can simulate a multi-threaded environment with the component, since it works asynchronously.

Thanks.
