### ISSUE TITLE
Error on buffer reading (Content does not start with ident char)

### ISSUE THREAD

**Issue by jperim** [digao-dalpiaz/DzSocket#12]
Hello, Digao
I already congratulate you on the component, I liked it a lot and adding it to my project.
I don't know if this would be the best place to ask you a question, but I'm sorry if it isn't.
Using DzSocket (Server/Client) by delphi, everything OK!
But you can use Server in Delphi, and send msg from another location, like: https://amritb.github.io/socketio-client-tool/v1/

Because I always get an error:
Error on buffer reading (Content does not start with ident char)

Could you help me with an example if possible?

Thanks!

**Comment by digao-dalpiaz** [comment]
Hello @jperim ,

Yes, sure, you can send all questions here.

DzSocket uses internal message predefined "header" to control message scope. So, you can't send or receive messages from another engine.

The component uses "commands" internally in the message. When you are using other component, there is no commands or message parts control, so there is no way to integrate these different engines.

You may use TClientSocket/TServerSocket (Delphi native components) to do that.
