### ISSUE TITLE
Send ansi raw string

### ISSUE THREAD

**Issue by PrzemWis** [digao-dalpiaz/DzSocket#14]
Very please add SendRawAnsiStr(const s: AnsiString) method
to the TDzTCPClient class to maintain compatibility with the TClientSocket/TServerSocket available in the environment.

**Comment by digao-dalpiaz** [comment]
Hello @PrzemWis ,

Do you need this method to communicate DzTCPClient with Standard TServerSocket?
I ask that because you cannot use DzSocket mixed with standard Delphi TClientSocket/TServerSocket. 
DzSocket uses internal header control embedded in raw string message.
