### ISSUE TITLE
FMX Support

### ISSUE THREAD

**Issue by zairzx** [digao-dalpiaz/DzSocket#7]
Hello, Does dzSocket and dzHtmlText support Delphi FMX

**Comment by digao-dalpiaz** [comment]
Hey @zairzx 

Yes, the **DzSocket** component supports **FMX**.

But for now, DzHTMLText only supports VCL.

**Comment by digao-dalpiaz** [comment]
**Important Note**: as DzSocket is based on Windows API, the component won't work if platform is not **Windows**.

**Comment by zairzx** [comment]
Ok, thank you
PS: dzHtmlText amazing !
I'll be waiting FMX too

**Comment by digao-dalpiaz** [comment]
Hi,

About **DzHTMLText** FMX support, you can follow it here:
https://github.com/digao-dalpiaz/DzHTMLText/issues/34
