### ISSUE TITLE
I hope clientsocket add reconnection times and delay.

### ISSUE THREAD

**Issue by cfzy** [digao-dalpiaz/DzSocket#9]
I hope clientsocket add reconnection times and delay.

**Comment by digao-dalpiaz** [comment]
In progress...

![demo_reconnect](https://user-images.githubusercontent.com/46692097/119011611-9c4f1600-b96b-11eb-9292-ff0fd48e79c0.png)
![design_reconnect_prop](https://user-images.githubusercontent.com/46692097/119011616-9d804300-b96b-11eb-9419-a0428b20fd04.png)

**Comment by cfzy** [comment]
Set the property to increase the number of connections, 0 will always be reconnected, 3 means only 3 reconnections.

**Comment by digao-dalpiaz** [comment]
Done!
New version 3.0 available
